# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    default_admin_email: '%env(string:DEFAULT_ADMIN_EMAIL)%'
    default_domain: '%env(string:ADMIN_URL_GENERATOR)%'
    default_scheme: http

    router.request_context.host: '%env(default:default_domain:SYMFONY_DEFAULT_ROUTE_HOST)%'
    router.request_context.scheme: '%env(default:default_scheme:SYMFONY_DEFAULT_ROUTE_SCHEME)%'
    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $nicokaUser: '%env(resolve:NICOKA_USER)%'
            $nicokaPassword: '%env(resolve:NICOKA_PASSWORD)%'
            $adminEmail: "%env(string:default:default_admin_email:ADMIN_EMAIL)%"
            $adminUrlGenerator: "%env(default:ADMIN_URL_GENERATOR)%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    doctrine.historySubcriber :
        class: App\EnventListener\historySubscriber
        tags:
            -{name: doctrine.event_subscriber}